name: Build and test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  conan_build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        profile: 
          - x86_64-gcc-14-release
          - x86_64-gcc-14-debug
          - x86_64-clang-18-release
          - x86_64-clang-18-debug

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y install ninja-build ccache

      - name: Install Conan
        run: pip install conan

      - name: Show Conan version
        run: conan --version

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: ~/.conan2/p/
          key: ${{ runner.os }}-conan-${{ hashFiles('**/conan.lock') }}

      - name: Detect Default Profile
        run: conan profile detect

      - name: Install Profiles
        run: conan config install https://github.com/ooonak/conanconf.git -t git --args="-b main" -sf=profiles -tf=profiles

      - name: Conan Install
        run: conan install . -pr ${{ matrix.profile }} --build=missing

      - name: Conan Build
        run: conan build . -pr ${{ matrix.profile }}

      - name: Conan Create
        run: conan create . -pr ${{ matrix.profile }}

